### PR TITLE
Add EnvironmentalDependencies product

### PR DESCRIPTION
**Pull request by maximkrouk**
Hi, the new GlobalDependencies target brings some ambiguity to library extensions. It's a draft PR to discuss ways to extend the package.
For example, I'd like to use it in https://github.com/capturecontext/composable-architecture-extensions, and provide some default implementations and also, maybe create a wrapper for https://github.com/capturecontext/swift-standard-clients. But I'd like to avoid forcing people to use a specific target from this package.
Probably it's not an issue if I had the `EnvironmentalDependencies` product in the case of swift-standard-clients, because clients are simple dependencies.
But in case of composable-architecture-extensions I tried to create `StoreSchedulers` environment and it is pattern-aware.
By writing this I understood that I could make `StoreSchedulersClient` and it should work, but I need `EnvironmentalDependencies` product anyway

I've chosen this name for the product to avoid taking too generic `Dependencies` name. Usually I have `Dependencies` local package for my apps, it should not be an issue, because I have a separate target for each dependency and no dependency is named `Dependency`. But maybe someone uses another approach and the name is taken, so `EnvironmentalDependencies` is more verbose and should not cause any conflicts.

### CODE REVIEW

**Comment by tgrapperon** [comment]
Hey @maximkrouk! Thanks for the PR!
I get the idea. I would lean toward `ComposableDependencies` instead of `EnvironmentalDependencies` for the name however, as I think it would make more sense when depending on the package `ComposableEnvironment`.
There's one issue with the two `_xxx` methods of `Dependencies` I would like to keep private though. I would like everything in `Dependencies` to be kept private for the user and yet access some of the methods or the inititializer from `Global/Composable.Environment`. I haven't found a way yet.

**Comment by maximkrouk** [comment]
Hopefully I'll update the PR in an hour adding this 🙂

**Comment by maximkrouk** [comment]
What do you think about declaring target dependencies in a more verbose manner and above products?
Like
```swift
.target(
  name: "ComposableEnvironment",
  dependencies: [
    .target(name: "ComposableDependencies"),
    .target(name: "_DependencyAliases"),
    .product(
      name: "ComposableArchitecture",
      package: "swift-composable-architecture"
    )
  ]
)
```
instead of 
```swift
.target(
  name: "ComposableEnvironment",
  dependencies: [
    .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
    "ComposableDependencies",
    "_DependencyAliases",
  ]
)
```
?

**Comment by maximkrouk** [comment]
- So I came to exporting separate pieces of Dependencies module (I also renamed private ones to have an underscore)
- To do so I had to extract `new` and `mergeFromUpstream` to global functions
- Changed naming a bit (to `_createDependencies()` and `_merge(_ upstream: Dependencies, to dependencies: inout Dependencies)` since now these declarations are at top-level scope
- I removed exports for _Dependencies and now it's contents are exported only via `ComposableDependencies`
- "private" functions are not exported, but if you explicitly `import _Dependencies` (which seems like a private thing and you probably won't use it at least unintentionally), you still able to use them

> And I'd like to ask what is`@implementationOnly import`? I've never seen it before 🙂

**Comment by tgrapperon** [comment]
This seems nice, I'll have a deeper look later.
`@_implementationOnly` doesn't expose to clients of the module the imported dependency.
`@_implementationOnly import DependencyAliases` allows to import and use `DependencyAliases`, but hides it to clients importing `GlobalEnvironment` for example. It acts as some kind of "import privately", so this can't be used with `Dependencies` because we would also hide `DependencyKey`, etc. but maybe something is possible with `_Dependencies`.

About the comment, I'm in favor of using explicit `.target(name:)` instead of string literals. I would like to keep using the shortest unambiguous form possible each time. Many packages authors are following this implicit rule, including Point-Free or Apple.

**Comment by maximkrouk** [comment]
Well, then making the PR "Ready for review"

**Review by tgrapperon — APPROVED** [review]
Thanks, @maximkrouk. I've managed to hide the exposed methods thanks to '@_implementationOnly'. The missing link was importing only the types instead of the whole module like you're doing in this PR. Since modifications are scattered among files you didn't touch here, I'll merge this one and build upon it.

**Pull request merged**
